[versions]
accompanistSystemuicontroller = "0.30.1"
activityCompose = "1.7.2"
agp = "8.2.0-alpha15"
androidGradlePlugin = "8.0.1"
appcompat = "1.6.1"
buildkonfigGradlePlugin = "0.13.3"
compose = "1.4.3"
coreKtx = "1.10.1"
coreSplashscreen = "1.0.1"
datastorePreferences = "1.0.0"
desugar_jdk_libs = "2.0.3"
firebaseBom = "32.2.0"
firebaseCrashlyticsGradle = "2.9.7"
googleServices = "4.3.15"
imageLoader = "1.4.0"
jtokkit = "0.5.0"
koin = "3.4.3"
kotlin = "1.9.0"
kotlinxDatetime = "0.4.0"
libresCompose = "1.1.8"
markdown = "0.4.1"
napier = "2.6.1"
openaiClient = "3.3.2"
playServicesAds = "22.2.0"
resources = "0.3.2"
settings = "1.0.0"
sqlDelight = "2.0.0"
uuid = "0.7.0"
voyager = "1.0.0-rc06"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
buildkonfig-gradle-plugin = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfigGradlePlugin" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle-plugin = { module = "io.github.skeptick.libres:gradle-plugin", version.ref = "libresCompose" }
image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoader" }
jtokkit = { module = "com.knuddels:jtokkit", version.ref = "jtokkit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
libres-compose = { module = "io.github.skeptick.libres:libres-compose", version.ref = "libresCompose" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "settings" }
multiplatform-settings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "settings" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
openai-client = { module = "com.aallam.openai:openai-client", version.ref = "openaiClient" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
resources = { module = "com.goncalossilva:resources", version.ref = "resources" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
voyager-navigator = { group = "cafe.adriel.voyager", name = "voyager-navigator", version.ref = "voyager" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
